version: '3.3'

volumes:
  mysql_data:
  static:

services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./masters_office/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/staticfiles/
  
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80