version: '3.3'

volumes:
  mysql_data_production:
  static:

services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql_data_production:/var/lib/mysql

  backend:
    image: maxsnork/masters_office
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/staticfiles

  gateway:
    image: maxsnork/masters_office_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80