version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    # image: maxsnork/masters_office    
    build: ./masters_office/
    env_file: .env
    volumes:
    - static:/backend_static
    depends_on:
      - db
  
  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
