version: '3.3'

volumes:
  pg_data_production:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: maxsnork/masters_office
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/staticfiles

  gateway:
    image: maxsnork/masters_office_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80