# Generated by Django 4.1.7 on 2023-10-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_alter_energydistrict_title'),
        ('users', '0002_add_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='energy_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='office.energydistrict', verbose_name='Энергорайон'),
            preserve_default=False,
        ),
    ]
