# Generated by Django 4.2.6 on 2024-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка'),
        ),
    ]
