# Generated by Django 4.2.6 on 2024-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalnotification_link_notification_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnotification',
            old_name='is_view',
            new_name='viewed',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_view',
            new_name='viewed',
        ),
        migrations.AlterField(
            model_name='historicalnotification',
            name='link',
            field=models.CharField(blank=True, help_text='Объект уведомления', max_length=1024, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Объект уведомления', max_length=1024, null=True, verbose_name='Ссылка'),
        ),
    ]
