# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер бригады')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Источник тепла')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Источник тепла',
                'verbose_name_plural': 'Источники тепла',
            },
        ),
        migrations.CreateModel(
            name='EnergyDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Энергорайон')),
            ],
            options={
                'verbose_name': 'Энергорайон',
                'verbose_name_plural': 'Энергорайоны',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('rank', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Разряд')),
                ('tab_number', models.SmallIntegerField(unique=True, verbose_name='Табельный номер')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=50, verbose_name='Должность')),
                ('walker', models.BooleanField(verbose_name='Может участвовать в обходах')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name_position'],
            },
        ),
        migrations.CreateModel(
            name='PostWalking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('number_post', models.PositiveIntegerField(verbose_name='Номер записи')),
                ('walk_date', models.DateTimeField(help_text='Введите дату в формате "ДД.ММ.ГГГГ"', verbose_name='Дата обхода')),
                ('planned', models.BooleanField(default=True, verbose_name='Плановый')),
                ('not_planned', models.BooleanField(default=False, verbose_name='Внеплановый')),
                ('task', models.TextField(default='Обход тепловой сети', max_length=250, verbose_name='Участок теплотрассы, задание мастера')),
                ('text', models.TextField(verbose_name='Замечания, выявленные при обходе')),
                ('plan', models.TextField(blank=True, default='---', verbose_name='Организационные мероприятия по устранению')),
                ('resolution', models.TextField(blank=True, default='---', verbose_name='Резолюция начальника энергорайона')),
                ('fix_date', models.DateField(blank=True, help_text='При отсутствии замечаний не заполняется', null=True, verbose_name='Дата устранения замечания')),
                ('transfer', models.CharField(blank=True, default='---', max_length=150, verbose_name='Перенос на ремонт в план на следующий месяц или на межотопительный период')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Запись в журнале обхода',
                'verbose_name_plural': 'Записи в Журналах обходов',
                'ordering': ['number_post'],
            },
        ),
    ]
