# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalking',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='office.district', verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='journal',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='office.journal', verbose_name='Запись в журнале обхода'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='members',
            field=models.ManyToManyField(related_name='brigade', to='office.personal', verbose_name='Члены бригады'),
        ),
        migrations.AddField(
            model_name='personal',
            name='energy_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='office.energydistrict', verbose_name='Энергорайон'),
        ),
        migrations.AddField(
            model_name='personal',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='office.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='journal',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='office.journal', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='district',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='brigadier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigadier', to='office.personal', verbose_name='Бригадир'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Бригада мастера'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(related_name='brigades', to='office.personal', verbose_name='Члены бригады'),
        ),
    ]
