# Generated by Django 4.1.7 on 2023-03-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalking',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='office.district', verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='journal',
            field=models.ForeignKey(help_text='Журнал, в котором будет запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='office.journal', verbose_name='Журнал'),
        ),
        migrations.AddField(
            model_name='personal',
            name='energy_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='office.energydistrict', verbose_name='Энергорайон'),
        ),
        migrations.AddField(
            model_name='personal',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='office.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='district',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
