# Generated by Django 4.1.7 on 2023-03-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_position',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigadier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigadier', to='office.personal', verbose_name='Бригадир')),
                ('member_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigade', to='office.personal', verbose_name='Член бригады_1')),
            ],
        ),
    ]
