# Generated by Django 4.1.7 on 2023-04-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='level',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='tree_id',
        ),
    ]
