# Generated by Django 4.1.7 on 2023-03-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0003_alter_district_slug_alter_position_name_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AddField(
            model_name='brigade',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Бригада мастера'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
