# Generated by Django 4.1.7 on 2023-04-15 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0003_remove_journal_parent_remove_postwalking_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postwalking',
            name='resolution',
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Резолюция')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания резолюции')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post_walking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='office.postwalking', verbose_name='Резолюция начальника энергорайона')),
            ],
            options={
                'verbose_name': 'Резолюция',
                'verbose_name_plural': 'Резолюции',
            },
        ),
    ]
