# Generated by Django 4.1.7 on 2023-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_brigade_options_brigade_master_brigade_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер бригады'),
        ),
    ]
