# Generated by Django 4.1.7 on 2023-04-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_remove_postwalking_resolution_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='post_walking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='office.postwalking', verbose_name='Резолюция записи'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='text',
            field=models.TextField(default='---', verbose_name='Резолюция начальника энергорайона'),
        ),
    ]
