# Generated by Django 4.1.7 on 2023-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_resolution_post_walking_alter_resolution_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='text',
            field=models.TextField(verbose_name='Резолюция начальника энергорайона'),
        ),
    ]
