# Generated by Django 4.1.7 on 2023-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_brigade_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energydistrict',
            options={'verbose_name': 'Энергорайон', 'verbose_name_plural': 'Энергорайоны'},
        ),
        migrations.AlterModelOptions(
            name='postwalking',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи в Журналах обходов'},
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='member_1',
        ),
        migrations.AddField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(related_name='brigades', to='office.personal'),
        ),
    ]
