# Generated by Django 4.1.7 on 2023-04-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_resolution_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postwalking',
            options={'ordering': ['-number_post'], 'verbose_name': 'Запись в журнале обхода', 'verbose_name_plural': 'Записи в Журналах обходов'},
        ),
    ]
