# Generated by Django 4.1.7 on 2023-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_energydistrict_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['last_name'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name_position'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='postwalking',
            options={'ordering': ['number_post'], 'verbose_name': 'Запись в журнале обхода', 'verbose_name_plural': 'Записи в Журналах обходов'},
        ),
        migrations.AddField(
            model_name='postwalking',
            name='not_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='planned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(related_name='brigades', to='office.personal', verbose_name='Члены бригады'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
