# Generated by Django 4.1.7 on 2023-03-26 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_personal_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalking',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postwalking',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postwalking',
            name='not_planned',
            field=models.BooleanField(default=False, verbose_name='Внеплановый'),
        ),
        migrations.AlterField(
            model_name='postwalking',
            name='planned',
            field=models.BooleanField(default=True, verbose_name='Плановый'),
        ),
    ]
