# Generated by Django 4.1.7 on 2023-04-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_postwalking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalking',
            name='journal',
            field=models.ForeignKey(help_text='Журнал, в котором будет запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='office.journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='post_walking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='office.postwalking', verbose_name='Резолюция для записи'),
        ),
    ]
