# Generated by Django 4.1.7 on 2023-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_postwalking_time_create_postwalking_time_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwalking',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='postwalking',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
