# Generated by Django 4.1.7 on 2023-03-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_postwalking_time_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postwalking',
            name='journal',
        ),
        migrations.AddField(
            model_name='postwalking',
            name='members',
            field=models.ManyToManyField(related_name='brigade', to='office.personal', verbose_name='Члены бригады'),
        ),
    ]
