# Generated by Django 4.1.7 on 2023-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_alter_postwalking_number_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwalking',
            name='number_post',
            field=models.PositiveIntegerField(verbose_name='Номер записи'),
        ),
    ]
