# Generated by Django 4.1.7 on 2023-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_alter_postwalking_number_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwalking',
            name='pub_date',
            field=models.DateTimeField(help_text='Введите дату в формате "ДД.ММ.ГГГГ"', verbose_name='Дата обхода'),
        ),
    ]
