# Generated by Django 4.1.7 on 2023-04-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_alter_postwalking_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postwalking',
            old_name='pub_date',
            new_name='walk_date',
        ),
    ]
