# Generated by Django 4.1.7 on 2023-10-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_add_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydistrict',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Энергорайон'),
        ),
    ]
