# Generated by Django 4.1.7 on 2023-10-18 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0014_alter_energydistrict_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
