# Generated by Django 4.2.6 on 2023-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_alter_district_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalking',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленная запись'),
        ),
    ]
