# Generated by Django 4.2.6 on 2023-10-31 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0017_alter_postwalking_walk_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRepairWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('number_post', models.PositiveIntegerField(verbose_name='Номер записи')),
                ('order', models.CharField(choices=[('Наряд', 'Наряд'), ('Распоряжение', 'Распоряжение')], help_text='наряду или распоряжению', max_length=30, verbose_name='Работы по')),
                ('number_order', models.PositiveIntegerField(verbose_name='Номера распоряжения/наряда')),
                ('description', models.TextField(verbose_name='Выполненные работы')),
                ('date_start_working', models.DateTimeField(verbose_name='Дата начала работ')),
                ('date_end_working', models.DateTimeField(verbose_name='Дата окончания работ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаленная запись')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_repair', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_repair', to='office.district', verbose_name='источник (район)')),
                ('journal', models.ForeignKey(help_text='Журнал, в котором будет запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_repair', to='office.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Запись в журнале ремонтных работ',
                'verbose_name_plural': 'Записи в журнале ремонтных работ',
                'ordering': ['-number_post'],
            },
        ),
    ]
