# Generated by Django 4.2.6 on 2023-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_postrepairwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postwalking',
            options={'ordering': ['-number_post'], 'verbose_name': 'Запись в журнале обхода', 'verbose_name_plural': 'Записи в журналах обходов'},
        ),
        migrations.AlterField(
            model_name='postrepairwork',
            name='number_order',
            field=models.PositiveIntegerField(verbose_name='Номер распоряжения/наряда'),
        ),
        migrations.AlterField(
            model_name='postrepairwork',
            name='number_post',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер записи'),
        ),
    ]
