# Generated by Django 4.2.6 on 2023-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_alter_postwalking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='energy_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='office.energydistrict', verbose_name='Энергорайон'),
            preserve_default=False,
        ),
    ]
