# Generated by Django 4.2.6 on 2023-11-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_district_energy_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrepairwork',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='postwalking',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
