# Generated by Django 4.2.6 on 2023-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_remove_postrepairwork_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrepairwork',
            name='adress',
            field=models.CharField(default='улица', max_length=200, verbose_name='Адрес (объект)'),
            preserve_default=False,
        ),
    ]
