# Generated by Django 4.2.6 on 2023-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0022_postrepairwork_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrepairwork',
            name='is_edit',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
        migrations.AddField(
            model_name='postwalking',
            name='is_edit',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
    ]
