# Generated by Django 4.2.6 on 2023-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0025_postorder_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postorder",
            name="date_end_working",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Работа закончена"
            ),
        ),
        migrations.AlterField(
            model_name="postorder",
            name="date_start_working",
            field=models.DateTimeField(verbose_name="К работе приступили"),
        ),
        migrations.AlterField(
            model_name="postorder",
            name="number_order",
            field=models.PositiveIntegerField(verbose_name="Номер наряда/распоряжения"),
        ),
        migrations.AlterField(
            model_name="postorder",
            name="order",
            field=models.CharField(
                choices=[("Наряд", "Наряд"), ("Распоряжение", "Распоряжение")],
                max_length=30,
                verbose_name="Наряд/распоряжение",
            ),
        ),
    ]
