# Generated by Django 4.2.6 on 2023-11-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0026_alter_postorder_date_end_working_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="foreman",
            field=models.BooleanField(
                default=False, verbose_name="Может быть производителем работ"
            ),
        ),
    ]
