# Generated by Django 4.2.6 on 2023-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0027_personal_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Уведомление просмотрено'),
        ),
        migrations.AlterField(
            model_name='postorder',
            name='order',
            field=models.CharField(choices=[('Наряд', 'Наряд'), ('Распоряжение', 'Распоряжение')], help_text='Номер присваивается автоматически', max_length=30, verbose_name='Наряд/распоряжение'),
        ),
    ]
