# Generated by Django 4.2.6 on 2023-11-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0028_resolution_viewed_alter_postorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydistrict',
            name='title',
            field=models.CharField(max_length=35, unique=True, verbose_name='Энергорайон'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='post_walking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution', to='office.postwalking', verbose_name='Резолюция для записи'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='text',
            field=models.TextField(verbose_name='Текст резолюции'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Резолюция просмотрена'),
        ),
    ]
