# Generated by Django 4.2.6 on 2023-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0029_alter_energydistrict_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='tab_number',
            field=models.IntegerField(unique=True, verbose_name='Табельный номер'),
        ),
    ]
