# Generated by Django 4.2.6 on 2023-12-07 20:20

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_alter_personal_tab_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'блок контента',
                'verbose_name_plural': 'Блоки контента',
            },
        ),
    ]
